In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [3]:
my_list = [1, 2, 3, 4, 5]
my_list

[1, 2, 3, 4, 5]

In [7]:
python_list = list(range(100))
python_list[:5]

[0, 1, 2, 3, 4]

In [10]:
import sys
sys.getsizeof(python_list[0])*len(python_list)

2800

In [11]:
python_np_array = np.arange(100)
python_np_array[:5]

array([0, 1, 2, 3, 4])

In [13]:
python_np_array.nbytes

800

In [14]:
import sys
sys.getsizeof(python_np_array[0])*len(python_np_array)

3200

In [17]:
import time

size = 100

list_1 = list(range(size))
list_2 = list(range(size))

start_time = time.time()
list_3 = [x+y for x, y in zip(list_1, list_2)]
end_time = time.time()

print(list_3)
print("List took: ", (end_time - start_time)*1000)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182, 184, 186, 188, 190, 192, 194, 196, 198]
List took:  0.1468658447265625


In [18]:
numpy_arr_1 = np.arange(size)
numpy_arr_2 = np.arange(size)
numpy_arr_1[:5], numpy_arr_2[:5]

(array([0, 1, 2, 3, 4]), array([0, 1, 2, 3, 4]))

In [31]:
start_time = time.time()
numpy_arr_3 = numpy_arr_1 + numpy_arr_2
print(numpy_arr_3[:5])
end_time = time.time()
print("Numpy took: ", (end_time - start_time)*1000)

[0 2 4 6 8]
Numpy took:  0.3142356872558594


In [ ]:
list_1 = list(range(5))
list_2 = list(range(5))
list_1, list_2
list_3 = list_1+list_2
list_3
#It is doing simple concatenation.Not addition

[0, 1, 2, 3, 4, 0, 1, 2, 3, 4]