In [1]:
import numpy as np

In [2]:
q1= np.array([
    [220,220,250],  #product A
    [150,180,210],  #product B
    [300,330,360]])  #product C

q2 = np.array([
    [209,231,259], #product A
    [155,192,222], #product B
    [310,340,375]]) #product C

In [3]:
q1+q2

array([[429, 451, 509],
       [305, 372, 432],
       [610, 670, 735]])

In [4]:
q2-q1

array([[-11,  11,   9],
       [  5,  12,  12],
       [ 10,  10,  15]])

In [5]:
q1 * q2

array([[ 45980,  50820,  64750],
       [ 23250,  34560,  46620],
       [ 93000, 112200, 135000]])

In [6]:
price = np.array([[10,20,30],[40,50,60],[70,80,90]])
rev = price * q2
rev

array([[ 2090,  4620,  7770],
       [ 6200,  9600, 13320],
       [21700, 27200, 33750]])

In [7]:
np.sum(rev)

np.int64(126250)

In [10]:
features = np.array([[2000,3],[1800,2]])  #area,sqft,bedrooms
weights = np.array([150,50000])  #weights for each feature

np.dot(features,weights)

array([450000, 370000])

In [12]:
c = np.array([1,2,3])
d = np.array([4,5,6])
np.cross(c,d)

array([-3,  6, -3])