In [1]:
import numpy as np

In [2]:
rev_1 = np.array([1, 2, 3])
rev_1.ndim

1

In [3]:
rev_2 = np.array([[1, 2, 3],[4,5,6]])
rev_2.ndim

2

In [4]:
rev_2

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
rev_2[1,2]

np.int64(6)

In [6]:
rev_2.shape

(2, 3)

In [7]:
rev_2.dtype

dtype('int64')

In [8]:
rev = np.array([[1, 12, 3],[4,10,6]], dtype=np.float16)
rev.dtype

dtype('float16')

In [9]:
rev.itemsize

2

In [10]:
rev.size

6

In [11]:
np.sort(rev)

array([[ 1.,  3., 12.],
       [ 4.,  6., 10.]], dtype=float16)

In [12]:
np.sort(rev,axis=None)

array([ 1.,  3.,  4.,  6., 10., 12.], dtype=float16)

In [13]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
print(np.arange(10,20,2))
print(np.arange(10,20))

[10 12 14 16 18]
[10 11 12 13 14 15 16 17 18 19]


In [16]:
np.linspace(1,10,30)

array([ 1.        ,  1.31034483,  1.62068966,  1.93103448,  2.24137931,
        2.55172414,  2.86206897,  3.17241379,  3.48275862,  3.79310345,
        4.10344828,  4.4137931 ,  4.72413793,  5.03448276,  5.34482759,
        5.65517241,  5.96551724,  6.27586207,  6.5862069 ,  6.89655172,
        7.20689655,  7.51724138,  7.82758621,  8.13793103,  8.44827586,
        8.75862069,  9.06896552,  9.37931034,  9.68965517, 10.        ])

In [18]:
rev.min()

np.float16(1.0)

In [19]:
rev.max()

np.float16(12.0)

In [21]:
rev.sum(axis=1)

array([16., 20.], dtype=float16)

In [22]:
rev

array([[ 1., 12.,  3.],
       [ 4., 10.,  6.]], dtype=float16)

In [23]:
for row in rev:
    print(row)

[ 1. 12.  3.]
[ 4. 10.  6.]


In [27]:
b = np.array([4,23,67,89])
print(np.sqrt(b))
print(np.std(b))

[2.         4.79583152 8.18535277 9.43398113]
33.84800584968042


np.float64(2.0)