In [1]:
import numpy as np

In [2]:
array_1 = np.array([1, 2, 3, 4, 5])
print(array_1[0:3])

[1 2 3]


In [3]:
print(array_1[3:])

[4 5]


In [8]:
print(array_1)
print(array_1[-1])
print(array_1[-2])

[1 2 3 4 5]
5
4


In [10]:
print(array_1)
print(array_1[-2:])

[1 2 3 4 5]
[4 5]


In [11]:
b = np.array([[1, 2, 3], 
              [4, 5, 6],
              [7, 8, 9]])

In [15]:
print(b[1,2])
print(b[2,0])

6
7


In [16]:
b[-1]

array([7, 8, 9])

In [19]:
b[-1,0:2]

array([7, 8])

In [23]:
c= np.array([[101,"Mira"],
            [102,"Sara"],
            [103,"Tina"]])

In [26]:
d = np.array([
             [101,250.67,"12-04-2025"],
             [102,300.50,"15-05-2025"],
             [103,225.50,"20-06-2025"]
             ])

In [27]:
np.hstack((c,d))

array([['101', 'Mira', '101', '250.67', '12-04-2025'],
       ['102', 'Sara', '102', '300.5', '15-05-2025'],
       ['103', 'Tina', '103', '225.5', '20-06-2025']], dtype='<U32')

In [28]:
e = np.array([
    [104,'Venkat'],
    [105,'Ravi'],
    [106,'Anil']
])

In [29]:
np.vstack((c,e))

array([['101', 'Mira'],
       ['102', 'Sara'],
       ['103', 'Tina'],
       ['104', 'Venkat'],
       ['105', 'Ravi'],
       ['106', 'Anil']], dtype='<U21')

In [ ]:
transactions = np.array([
    [101,250.67,"12-04-2025"],
    [102,300.50,"15-05-2025"],
    [103,225.50,"20-06-2025"],
    [104,400.00,"25-04-2025"],
    [105,150.75,"30-04-2025"],
    [106,350.20,"05-05-2025"],
    [107,275.30,"10-05-2025"]

])